apps/admin/controllers.py
from google.appengine.api import search
import flask
from flask import Blueprint

from apps.admin.models import Activity
from apps.users import decor
from util.BaseModel import GENERAL_INDEX, BaseModel

admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


@admin_blueprint.route('/')
@decor.admin_required
def dashboard():
    return flask.render_template('dashboard.html',
                                 navbar=admin_area.navbar,
                                 recent_activity=Activity.query().order(-Activity.date_created))


@admin_blueprint.route('search/')
@decor.admin_required
def admin_search():
    query = flask.request.args.get('q', '').strip()

    if query:
        index = search.Index(name=GENERAL_INDEX)
        results = index.search(query)
        number_found = results.number_found
    else:
        results = None
        number_found = None

    return flask.render_template(
        'search.html',
        query=query,
        get_from_search_doc=BaseModel.get_from_search_doc,
        navbar=admin_area.navbar,
        number_found=number_found,
        results=results)


#
# Maps model to admin view

from app import app

app.register_blueprint(admin_blueprint, url_prefix='/admin/')

from apps.admin.register import admin_area

templates/401.html
{% extends "base-middle-page.html" %}

{% block title %}
    401: Not Authorized
{% endblock %}

{% block body %}
    <p><i class="uk-icon-ban uk-icon-large"></i></p>
    <h1>401: Not Authorized</h1>
    <p>You are not authorized to access this resource.</p>
{% endblock %}

templates/405.html
{% extends "base-middle-page.html" %}

{% block title %}
    405: Method Not Allowed
{% endblock %}

{% block body %}
    <p><i class="uk-icon-compass uk-icon-large"></i></p>
    <h1>405: Method Not Allowed</h1>
    <p>The method you used to post to this URL is not supported by the specified controller.</p>
{% endblock %}

templates/_dump.html
<table>
    {% for k, v in items %}
        <tr>
            <th>{{ k }}</th>
            <td>{{ v }}</td>
        </tr>
    {% endfor %}
</table>

templates/base-middle-page.html
{% extends "base.html" %}
{% block html_tag %}
    <html class="uk-height-1-1">
{% endblock %}

{% block body_tag %}
    <body class="uk-height-1-1">
{% endblock %}

{% block navbar %}
{% endblock %}

{% block container_begin %}
    <div class="uk-vertical-align uk-text-center uk-height-1-1">
    <div class="uk-vertical-align-middle">

{% endblock %}
{% block container_end %}
    </div>
    </div>
{% endblock %}

templates/base.html
{# base.html #}<!DOCTYPE html>
{% block html_tag %}
    <html lang="en">
{% endblock %}
<head>
    <title>{% block title %}NAME THIS PAGE{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/all.css">
    {% block head %}
    {% endblock %}
</head>

{% block body_tag %}
    <body>
{% endblock %}

{% block container_begin %}
    <div class="uk-container uk-container-center">
{% endblock %}

{#{% block debug_area %}#}
{#    <pre>{{ session.items() }}</pre>#}
{#{% endblock %}#}

{% block navbar %}
    <nav class="uk-navbar">
        {% block navbar_brand %}
            <ul class="uk-navbar-nav">
                <li><a class="uk-navbar-brand" href="/">{{ config.site_name }}</a></li>
            </ul>
        {% endblock %}
        {% block navbar_main %}
        {% endblock %}
        <div class="uk-navbar-flip">
            {% block navbar_search %}
            {% endblock %}
            {% block nabar_user %}
                <ul class="uk-navbar-nav">
                    {% if (not current_account) or current_account.is_anonymous %}
                        <li><a href="{{ url_for('users.login') }}"><i class="uk-icon-sign-in"></i> Login</a></li>
                    {% else %}
                        <li class="uk-parent" data-uk-dropdown>
                            <a href=""><i class="uk-icon-user"></i></a>

                            <div class="uk-dropdown uk-dropdown-navbar">
                                <ul class="uk-nav uk-nav-navbar">
                                    <li class="uk-nav-header">{{ current_account.display_name }}</li>
                                    <li><a href="{{ url_for('users.profile') }}"><i class="uk-icon-user"></i> My Profile</a></li>
                                    {% if current_tenant %}
                                        <li class="uk-nav-header">{{ current_tenant.name }}</li>
                                        <li><a href="{{ url_for('tenants.tenant_overview') }}"><i class="uk-icon-briefcase"></i> My Account</a></li>
                                        {% if current_account.tenant_count > 1 %}
                                            <li><a href="{{ url_for('tenants.choose') }}"><i class="uk-icon-institution"></i> Change Account</a></li>
                                        {% endif %}
                                    {% endif %}
                                    {% if current_account.is_superuser %}
                                        <li class="uk-nav-divider"></li>
                                        <li><a href="{{ url_for('admin.dashboard') }}"><i class="uk-icon-gears"></i> Admin</a></li>
                                    {% endif %}
                                    <li class="uk-nav-divider"></li>
                                    <li><a href="{{ url_for('users.logout') }}"><i class="uk-icon-sign-out"></i> Logout</a></li>
                                </ul>
                            </div>
                        </li>
                    {% endif %}
                </ul>

            {% endblock %}
        </div>
    </nav>
{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block body %}{% endblock %}

{% block container_end %}
    </div>
{% endblock %}

{% block base_scripts %}
    <script src="/static/all.js"></script>

    {% block csrf_js %}
        <script type="text/javascript">
            $.ajaxPrefilter(function (options, originalOptions, jqXHR) {
                jqXHR.setRequestHeader('X-CSRFToken', "{{ csrf_token() }}");
            });
            // x_find_csrf_token {{ csrf_token() }}
        </script>
    {% endblock %}
    <script>

    </script>
    <script>
        moment.locale("en");
    </script>

    <script type="text/javascript">
        $(function () {
            $('.parsley-validate').parsley({
                successClass: 'uk-text-success',
                errorClass: 'uk-text-danger',
                errorsWrapper: '<div></div>',
                errorTemplate: '<div class="uk-alert uk-alert-warning"></div>'
            });
        });
    </script>

{% endblock %}
{% block notifications %}
    {% include "components/notifications.html" %}
{% endblock %}
{% block modals %}
{% endblock %}
{% block scripts %}
{% endblock %}

</body>
</html>

templates/page.html
{% extends "base.html" %}

{% block head %}
    {% if page.meta_description %}
        <meta name="description" content="{{ page.meta_description }}">
    {% endif %}
    {% if page.meta_keywords %}
        <meta name="keywords" content="{{ page.meta_keywords }}">
    {% endif %}
    {% if page.meta_author %}
        <meta name="author" content="{{ page.meta_author }}">
    {% endif %}
{% endblock %}

{% block title %}
    {{ page.title }}
{% endblock %}

{% block body %}
    {{ page.get_rendered_content() }}
{% endblock %}