apps/admin/models.py
from google.appengine.ext import ndb
from google.appengine.ext.ndb.polymodel import PolyModel

from util.BaseModel import BaseModel


class Activity(BaseModel, PolyModel):
    user = ndb.KeyProperty(kind='UserAccount')
    subject = ndb.KeyProperty()
    type = ndb.StringProperty()
    tags = ndb.StringProperty(repeated=True)

    def __str__(self):
        if self.user:
            user = self.user.get()
        else:
            user = '<No one>'

        if self.subject:
            subject = self.subject.get()
        else:
            subject = ''

        return u'%s: %s[%s] <%s>' % (user, subject, self.type, self.tags)

apps/admin/__init__.py
import controllers

apps/admin/controllers.py
from google.appengine.api import search
import flask
from flask import Blueprint

from apps.admin.models import Activity
from apps.users import decor
from util.BaseModel import GENERAL_INDEX, BaseModel

admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


@admin_blueprint.route('/')
@decor.admin_required
def dashboard():
    return flask.render_template('dashboard.html',
                                 navbar=admin_area.navbar,
                                 recent_activity=Activity.query().order(-Activity.date_created))


@admin_blueprint.route('search/')
@decor.admin_required
def admin_search():
    query = flask.request.args.get('q', '').strip()

    if query:
        index = search.Index(name=GENERAL_INDEX)
        results = index.search(query)
        number_found = results.number_found
    else:
        results = None
        number_found = None

    return flask.render_template(
        'search.html',
        query=query,
        get_from_search_doc=BaseModel.get_from_search_doc,
        navbar=admin_area.navbar,
        number_found=number_found,
        results=results)


#
# Maps model to admin view

from app import app

app.register_blueprint(admin_blueprint, url_prefix='/admin/')

from apps.admin.register import admin_area

apps/admin/templates/dashboard.html
{% extends "admin/admin-base.html" %}

{% block title %}Admin Dashboard{% endblock %}

{% block body %}
    <table class="uk-table uk-table-condensed">
        <caption>Recent Activity</caption>
        {% for activity in recent_activity %}
            <tr>
                {% for tag in activity.tags %}
                    <td>
                        {{ moment(activity.date_created).fromTime(global_now) }}
                    </td>
                    <td>
                        {% if get_object_view(activity.user) %}
                            <a href="{{ get_object_view(activity.user) }}">{{ activity.user.get() }}</a>
                        {% else %}
                            {{ activity.user.get() }}
                        {% endif %}
                    </td>
                    <td>
                        {{ activity.type }}
                    </td>
                    <td>
                        {% if get_object_view(activity.subject) %}
                            <a href="{{ get_object_view(activity.subject) }}">{{ activity.subject.get() }}</a>
                        {% else %}
                            {{ activity.subject.get() }}
                        {% endif %}
                    </td>
                    <td>
                        {{ ', '.join(activity.tags) }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

apps/admin/templates/search.html
{% extends "admin/admin-base.html" %}

{% block title %}Search{% endblock %}

{% block body %}
    <div class="uk-margin">
        <form method="get" action="{{ url_for('admin.admin_search') }}" class="uk-form uk-width-1-1">
            <div class="uk-grid uk-grid-collapse">
                <div class="uk-width-9-10">
                <input type="text" name="q" value="{{ query }}" placeholder="Search String" class="uk-width-1-1 uk-form-large">
                </div>
                <div class="uk-width-1-10">
                <button class="uk-button uk-button-primary uk-button-large uk-width-1-1" type="submit"><i class="uk-icon-search"></i> Search</button>
                </div>
            </div>
        </form>
    </div>

    {% if query %}
        {% if number_found %}
            {% if number_found == 1 %}
                <p class="uk-text-bold uk-text-center">Your query (<span class="uk-text-primary">"{{ query }}"</span>) returned 1 result.</p>
            {% else %}
                <p class="uk-text-bold uk-text-center">Your query (<span class="uk-text-primary">"{{ query }}"</span>) returned {{ number_found }} results.</p>
            {% endif %}
        {% else %}
            <p class="uk-text-bold uk-text-center">Your query (<span class="uk-text-primary">"{{ query }}"</span>) returned no results.</p>
        {% endif %}
        <hr>
        <dl class="uk-description-list-line">
        {% if results %}
            {% for result in results %}
                {% set current_object = get_from_search_doc(result) %}
                <dt>
                    {% if get_object_view(current_object) %}
                        <a href="{{ get_object_view(current_object) }}">{{ current_object }}</a>
                    {% else %}
                        {{ current_object }}
                    {% endif %}
                    <div class="uk-badge">{{ current_object.get_class_badge() }}</div>
                </dt>
            {% endfor %}
        {% endif %}
        </dl>
    {% endif %}
{% endblock %}